baseURL = "/"
# title = "Vertica Integrators Guide"
# uglyurls = true
relativeURLs = true

# Language settings
# contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["github.com/google/docsy", "github.com/google/docsy/dependencies"]

# Hugo modules
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"

# Will give values to .Lastmod etc.
enableGitInfo = true

# Comment out to enable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]


#################### Different from hugo branch ####################

# You can add your own taxonomies
#[taxonomies]
#tag = "tags"
#category = "categories"


# Release versioning
#[[params.versions]]
#  version = "v1"
#  url = "https://localhost:1313"

# version_menu = "Releases"

####################################################################



# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
# [permalinks]
# blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"


[markup]

  [markup.goldmark.renderer]
     # this setting lets us use shortcodes in code blocks. Note that for shortcodes to work, 
     # you must not have Hugo interpret markdown within shortcodes. I,e. {{< codevar >}} instead
     # of {{% codevar %}}. 
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax = "true"

  [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.tableOfContents]
      endLevel = 4
      ordered = false
      startLevel = 1

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
# [outputs]
# section = ["HTML", "print", "RSS"]




# Force everything to use doc page format
[cascade]
  type = "docs"


# see https://gohugo.io/content-management/related/#configure-related-content
# for details. These settings are used by the see also shortcode. 
[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'categories'
  weight = 40
[[related.indices]]
  name = 'date'
  weight = 0

[params]
  ui.sidebar_menu_foldable = true
  ui.ul_show = 4


#[[menu.main]]
#    name = "Academy"
#    weight = 10
#    url = "https://academy.vertica.com/"

#[[menu.main]]
#    name = "Forum"
#    weight = 20
#    url = "https://forum.vertica.com/"

#[[menu.main]]
#    name = "Support"
#    weight = 30
#    url = "https://www.microfocus.com/en-us/support/Vertica%20Analytics%20Platform"


#[module]
# We use mounts to virtually mount directories in the Hugo project.
# The following makes sure the default static directory is mounted
# in the project. Once you use a mount in Hugo, it wipes out the 
# default mapping.
#[[module.mounts]]
#  source = 'static'
#  target = 'static'


#[[module.mounts]]
#  source = '../sdk/'
#  target = 'static'